# DNS服务
[service]
# 监听IP，留空则监听所有地址
ip=""

# 内部域名后缀，例如*.uam则填写.test.
# 注意要以.结尾
# 如果留空，则不启用内部域名解析的功能，同时存储器设置也不会生效
internalSuffix=["test.com."]

# 退出等待时间
quitWaitTimeout=5

# 启用DNS代理时，上游DNS服务地址
# 支持的DNS格式示例如下：
# udp://1.1.1.1:53
# tcp://1.1.1.1:53
# tls://1.1.1.1:853
# https://1.1.1.1/dns-query
[service.upstream]
addrs=["udp://1.1.1.1:53", "tcp://1.1.1.1:53", "tls://1.1.1.1:853", "https://1.1.1.1/dns-query"]

# 向上游DNS over HTTP/HTTPS服务查询时使用的HTTP代理地址
# 目前仅支持向上游HTTP/HTTPS服务发起查询时使用代理，且只能使用HTTP代理
httpProxy=""

# DNS over UDP服务的端口，如果为0则不启用该服务
[service.udp]
port=53

# DNS over TCP服务的端口，默认53端口，如果为0则不启用该服务
[service.tcp]
port=53

# DNS over TLS服务的端口，默认853端口，如果为0则不启用该服务
[service.tls]
port=853

# DNS over TLS服务的cert文件地址，不启用该服务时可以留空
certFile="./server.pem"

# DNS over TLS服务的key文件地址，不启用该服务时可以留空
keyFile="./server.key"

# HTTP服务的端口，默认80端口，如果为0则不启用该服务
[service.http]
port=80

# HTTPS服务的端口，默认443端口，留空则不启用该服务
sslPort=443

# HTTPS服务的证书文件(cert/pem)路径，不启用该服务时可以留空
certFile="./server.pem"

# HTTPS服务的私钥文件(key)路径，不启用该服务时可以留空
keyFile="./server.key"

# HTTP API 密钥，做为header中的Authorization参数值，留空则不需要验证
authorization = "123456"

# HTTP DNS (DoH) 查询路径，留空则不启用本功能
dnsQueryPath = "/dns-query"
# HTTP DNS 查询是否需要验证密钥
dnsQueryAuth = false

# HTTP JSON 查询域名路径，留空则不启用本功能
jsonQueryPath = "/resolve"
# HTTP JSON 查询是否需要验证密钥
jsonQueryAuth = false

# HTTP API 注册域名路径，留空则不启用本功能
registerPath = "/register"
# HTTP API 注册域名是否需要验证密钥
registerAuth = true

# HTTP API 删除域名路径，留空则不启用本功能
deletePath = "/delete"
# HTTP API 删除域名是否需要验证密钥
deleteAuth = true

[storage]
# redis的配置示例
#type="redis"
#config="""
#{
#  "addr": "127.0.0.1:6379",
#  "database": 0,
#  "password": "",
#  "prefix": "dns:",
#  "useTTL": false
#}
#"""

# voltdb的配置示例
type="voltdb"
config="""
{
  "addr": "127.0.0.1:21212",
  "database": "domain",
  "username": "",
  "password": "",
  "useTTL": false
}
"""

[logger]
# 记录级别: debug(默认)/info/warn/error
level="debug"

# 日志输出，填写日志文件的存储路径，如果留空则输出到控制台
output=""

# 日志时间格式，默认：y年-m月-d日 h时:i分:s秒
timeFormat="y-m-d h:i:s"

# 日志编码：console默认/json
encode="console"

# 在控制台输出时不使用颜色
noColor=false

# 日志文件的权限，默认：0600
# fileMode=0600
